stages:
  - build
  - deploy
  
build in gitlab:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -f .docker/Dockerfile --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - develop
    - test
    - master
    - devops
  when: manual
  tags:
    - docker

build in dockerhub:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD" $DOCKER_HUB_REGISTRY
  script:
    - docker build -f .docker/Dockerfile --pull -t "$DOCKER_HUB_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" -t "$DOCKER_HUB_REGISTRY_IMAGE:latest" .
    - docker push "$DOCKER_HUB_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker push "$DOCKER_HUB_REGISTRY_IMAGE:latest"
  only:
    - develop
    - test
    - master
    - devops
  when: manual
  tags:
    - docker

deploy to dev:
  image: docker:latest
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
  script:
    - chmod 600 $SSH_PRIVATE_KEY
    - scp -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no ./.docker/docker-compose-standing.yml student@books-exchange-dev.spring-intensive-2021.simbirsoft1.com:/home/student/docker
    - scp -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no ./.docker/deploy.sh student@books-exchange-dev.spring-intensive-2021.simbirsoft1.com:/home/student/docker
    - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no student@books-exchange-dev.spring-intensive-2021.simbirsoft1.com 'sudo bash /home/student/docker/deploy.sh'
  environment:
    name: devops/$CI_COMMIT_REF_NAME
  only:
    - develop
    - test
    - master
    - devops
  when: manual
  tags:
    - docker

deploy to test:
  image: docker:latest
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
  script:
    - chmod 600 $SSH_PRIVATE_KEY_TEST
    - scp -i $SSH_PRIVATE_KEY_TEST -o StrictHostKeyChecking=no ./.docker/docker-compose-standing.yml student@books-exchange-test.spring-intensive-2021.simbirsoft1.com:/home/student/docker
    - scp -i $SSH_PRIVATE_KEY_TEST -o StrictHostKeyChecking=no ./.docker/deploy.sh student@books-exchange-test.spring-intensive-2021.simbirsoft1.com:/home/student/docker
    - ssh -i $SSH_PRIVATE_KEY_TEST -o StrictHostKeyChecking=no student@books-exchange-test.spring-intensive-2021.simbirsoft1.com 'sudo bash /home/student/docker/deploy.sh'
  environment:
    name: devops/$CI_COMMIT_REF_NAME
  only:
    - develop
    - test
    - master
    - devops
  when: manual
  tags:
    - docker
